all:
  children:
    web:
      hosts:
        web-01:
          ansible_host: 10.10.10.10
    k3s_master:
      hosts:
        k3s-master:
          ansible_host: 10.10.10.40
    k3s_worker:
      hosts:
        k3s-worker:
          ansible_host: 10.10.10.41
    mon:
      hosts:
        mon-01:
          ansible_host: 10.10.10.30
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/lab_key
